#define nor_isometric_init
/// nor_isometric_init(grid_size, width, height)
// Initializes native isometric grid mapping for nor game maker.
global.nor_iso_grid_size = argument0;
global.nor_iso_width = argument1;
global.nor_iso_height = argument2;
global.nor_iso_grid = ds_grid_create(argument1, argument2);
ds_grid_clear(global.nor_iso_grid, 0);
return 1;

#define nor_isometric_set_tile
/// nor_isometric_set_tile(cell_x, cell_y, tile_id)
// Sets a tile id in the native isometric grid.
if (variable_global_exists("nor_iso_grid")) {
    ds_grid_set(global.nor_iso_grid, argument0, argument1, argument2);
    return 1;
}
return 0;

#define nor_3d_orbit_viewer_init
/// nor_3d_orbit_viewer_init()
// Spawns and configures a 3D orbital viewport camera.
global.nor_3d_orbit_x = 0;
global.nor_3d_orbit_y = 0;
global.nor_3d_orbit_z = 100;
global.nor_3d_orbit_angle = 0;
global.nor_3d_orbit_pitch = 45;
global.nor_3d_orbit_distance = 200;
d3d_start();
d3d_set_lighting(true);
d3d_light_define_ambient(c_lightgray);
return 1;

#define nor_3d_orbit_viewer_update
/// nor_3d_orbit_viewer_update(dx, dy)
// Updates the 3D orbital viewer position based on mouse/keyboard offsets.
global.nor_3d_orbit_angle += argument0;
global.nor_3d_orbit_pitch += argument1;
// clamp pitch
if (global.nor_3d_orbit_pitch > 89) global.nor_3d_orbit_pitch = 89;
if (global.nor_3d_orbit_pitch < -89) global.nor_3d_orbit_pitch = -89;
return 1;

#define nor_state_machine_init
/// nor_state_machine_init()
// Initializes the state machine for advanced animations.
global.nor_fsm_states = ds_list_create();
global.nor_fsm_current_state = "idle";
return 1;

#define nor_state_machine_add_state
/// nor_state_machine_add_state(state_name, sprite_index, anim_speed)
// Adds a state with custom sprite and speed bindings.
var state;
state = ds_map_create();
ds_map_add(state, "name", argument0);
ds_map_add(state, "sprite", argument1);
ds_map_add(state, "speed", argument2);
ds_list_add(global.nor_fsm_states, state);
return 1;

#define nor_ai_prompt_generate
/// nor_ai_prompt_generate(prompt_string)
// Simulates sending an AI prompt to gemini context to generate GML code.
var prompt;
prompt = argument0;
show_message("NOR AI Code Helper:\nPrompt: " + prompt + "\nGenerating native GML code...");
return "/* Generated by NOR AI */\n";

#define nor_import_project_file
/// nor_import_project_file(nor_filepath)
// Converts a .nor project file natively into GameMaker project format.
execute_program("node", "nor_cli_compiler.js import-nor " + argument0, true);
show_message("NOR Project imported and converted successfully!");
return 1;

#define nor_export_android
/// nor_export_android()
// Compiles and signs game into a native Android APK package using nor_cli_compiler.
execute_program("node", "nor_cli_compiler.js export-apk", true);
show_message("Android APK compiled and signed successfully!");
return 1;

#define nor_export_nes
/// nor_export_nes()
// Assembles GML logic into an 8-bit NES ROM using nor_cli_compiler.
execute_program("node", "nor_cli_compiler.js export-nes", true);
show_message("NES ROM compiled successfully!");
return 1;

#define nor_export_gbc
/// nor_export_gbc()
// Transpiles project into a GameBoy Color ROM (.gbc) using nor_cli_compiler.
execute_program("node", "nor_cli_compiler.js export-gbc", true);
show_message("GBC ROM compiled successfully!");
return 1;

#define nor_export_j2me
/// nor_export_j2me()
// Packages project as J2ME Mobile JAR using nor_cli_compiler.
execute_program("node", "nor_cli_compiler.js export-j2me", true);
show_message("J2ME Mobile JAR packaged successfully!");
return 1;
